# Generated by Django 5.2.17 on 2026-09-29 17:59

import contas.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='matrícula')),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('perfil', models.CharField(choices=[('SERVIDOR', 'Servidor'), ('ALMOXARIFE', 'Almoxarife'), ('GESTOR', 'Gestor do almoxarifado')], default='SERVIDOR', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acessa o Django Admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['nome'],
            },
            managers=[
                ('objects', contas.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('cota_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para não limitar o consumo do setor.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cota mensal (R$)')),
                ('chefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores_chefiados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'setores',
                'ordering': ['sigla'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='contas.setor'),
        ),
    ]
