# Generated by Django 5.2.17 on 2026-09-29 17:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150, verbose_name='razão social')),
                ('cnpj', models.CharField(help_text='Somente números.', max_length=14, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'fornecedores',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=7, unique=True, verbose_name='competência')),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('valor_entradas', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_saidas', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_ajustes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_estoque', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fechado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fechamento de competência',
                'verbose_name_plural': 'fechamentos de competência',
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=20, verbose_name='nº da nota fiscal')),
                ('data_recebimento', models.DateField(verbose_name='data de recebimento')),
                ('empenho', models.CharField(blank=True, max_length=20, verbose_name='nota de empenho')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='estoque.fornecedor')),
            ],
            options={
                'ordering': ['-data_recebimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('RESMA', 'Resma'), ('RL', 'Rolo'), ('FR', 'Frasco'), ('L', 'Litro'), ('KG', 'Quilo'), ('PAR', 'Par')], default='UN', max_length=10)),
                ('estoque_minimo', models.PositiveIntegerField(default=0, verbose_name='estoque mínimo')),
                ('estoque_maximo', models.PositiveIntegerField(default=0, verbose_name='estoque máximo')),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade_em_estoque', models.IntegerField(default=0, editable=False)),
                ('quantidade_reservada', models.IntegerField(default=0, editable=False)),
                ('custo_medio', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='estoque.categoria')),
            ],
            options={
                'verbose_name_plural': 'materiais',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor unitário')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.entrada')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.material')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE_ENTRADA', 'Ajuste de inventário (+)'), ('AJUSTE_SAIDA', 'Ajuste de inventário (−)')], max_length=20)),
                ('data', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('custo_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_quantidade', models.IntegerField()),
                ('saldo_custo_medio', models.DecimalField(decimal_places=4, max_digits=14)),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.entrada')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.material')),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'ordering': ['id'],
            },
        ),
    ]
