# Generated by Django 5.2.17 on 2026-09-29 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('estoque', '0001_initial'),
        ('requisicoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='requisicoes.requisicao'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contas.setor'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(fields=('fornecedor', 'numero_nota'), name='entrada_nota_unica_por_fornecedor'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_em_estoque__gte', 0)), name='material_estoque_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_reservada__gte', 0)), name='material_reserva_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_maximo__gte', models.F('estoque_minimo'))), name='material_maximo_gte_minimo'),
        ),
        migrations.AddConstraint(
            model_name='itementrada',
            constraint=models.UniqueConstraint(fields=('entrada', 'material'), name='item_entrada_material_unico'),
        ),
        migrations.AddConstraint(
            model_name='itementrada',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_entrada_quantidade_positiva'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['material', 'id'], name='estoque_mov_materia_4c375e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['data'], name='estoque_mov_data_8656da_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['setor', 'data'], name='estoque_mov_setor_i_6ddc51_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='movimentacao_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_quantidade__gte', 0)), name='movimentacao_saldo_nao_negativo'),
        ),
    ]
