# Generated by Django 5.2.17 on 2026-09-29 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Aguardando aprovação'), ('AGUARDANDO_GESTOR', 'Aguardando gestor'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('ATENDIDA', 'Atendida'), ('ATENDIDA_PARCIALMENTE', 'Atendida parcialmente'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=30)),
                ('finalidade', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('valor_atendido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('requisitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='contas.setor')),
            ],
            options={
                'verbose_name': 'requisição',
                'verbose_name_plural': 'requisições',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField()),
                ('quantidade_aprovada', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade_reservada', models.PositiveIntegerField(default=0)),
                ('quantidade_atendida', models.PositiveIntegerField(blank=True, null=True)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.material')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='requisicoes.requisicao')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_status', models.CharField(blank=True, choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Aguardando aprovação'), ('AGUARDANDO_GESTOR', 'Aguardando gestor'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('ATENDIDA', 'Atendida'), ('ATENDIDA_PARCIALMENTE', 'Atendida parcialmente'), ('CANCELADA', 'Cancelada')], max_length=30)),
                ('para_status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Aguardando aprovação'), ('AGUARDANDO_GESTOR', 'Aguardando gestor'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('ATENDIDA', 'Atendida'), ('ATENDIDA_PARCIALMENTE', 'Atendida parcialmente'), ('CANCELADA', 'Cancelada')], max_length=30)),
                ('quando', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='requisicoes.requisicao')),
            ],
            options={
                'ordering': ['quando', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['status'], name='requisicoes_status_c8c97e_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['setor', 'status'], name='requisicoes_setor_i_777c8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemrequisicao',
            constraint=models.UniqueConstraint(fields=('requisicao', 'material'), name='item_requisicao_material_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemrequisicao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_solicitada__gt', 0)), name='item_requisicao_quantidade_positiva'),
        ),
    ]
